window.appConfig = {
    clientId: "e658f6511ea84e158842b657cc02f609",
    baseUrl: "drixx.com",
    statusUrl: "https://status.drixx.com",
    logo: {
      darkThemeUrl:
              "https://uploads-ssl.webflow.com/5f478771e161508c2a99cdd5/5fc530ab785eba6b4e47cd41_logo-drixx.svg",
      lightThemeUrl:
              "https://uploads-ssl.webflow.com/5f478771e161508c2a99cdd5/5fc530ab785eba6b4e47cd41_logo-drixx.svg",
    },
    termsUrl: 'https://www.drixx.com/terms-conditions',
    defaultSymbol: "BTC-PERP",
    homepageUrl: "/",
    defaultLang: "en-US",
    defaultTheme: "dark",
    widgets: {
      futures: [{"id":"history","indicators":[{"key":"publicTrades"},{"key":"createLimitOrder"}]},{"id":"chart","indicators":[{"key":"chart"}]},{"id":"chart-depth","indicators":[{"key":"chartDepths"}]},{"id":"create-order","indicators":[{"key":"createLimitOrder"},{"key":"createMarketOrder"}]},{"id":"positions","indicators":[{"key":"positions"},{"key":"openOrders"},{"key":"accountTrades"},{"key":"closedOrders"}]},{"id":"orders","indicators":[{"key":"orderBook"}]},{"id":"account-summary","indicators":[{"key":"accountSummary"}]},{"id":"contract-details","indicators":[{"key":"contractDetails"}]}],
      options: [{}]
    },
    layouts: {
      futures_layouts:{
        "lg":[
          {
            "w":2,
            "h":60,
            "x":0,
            "y":0,
            "i":"history",
            "minW":2,
            "minH":20,
            "moved":false,
            "static":false
          },
          {
            "w":6,
            "h":44,
            "x":2,
            "y":0,
            "i":"chart",
            "minW":3,
            "minH":25,
            "moved":false,
            "static":false
          },
          {
            "w":6,
            "h":16,
            "x":2,
            "y":44,
            "i":"chart-depth",
            "minW":1,
            "minH":10,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":60,
            "x":8,
            "y":0,
            "i":"create-order",
            "minW":2,
            "minH":20,
            "moved":false,
            "static":false
          },
          {
            "w":8,
            "h":30,
            "x":2,
            "y":60,
            "i":"positions",
            "minW":4,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":60,
            "x":10,
            "y":0,
            "i":"orders",
            "minW":1,
            "minH":20,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":30,
            "x":10,
            "y":60,
            "i":"account-summary",
            "minW":1,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":30,
            "x":0,
            "y":60,
            "i":"contract-details",
            "minW":2,
            "minH":20,
            "moved":false,
            "static":false
          }
        ],
        "md":[
          {
            "i":"history",
            "x":0,
            "y":0,
            "w":6,
            "h":20,
            "minH":20,
            "minW":2
          },
          {
            "i":"contract-details",
            "x":0,
            "y":4,
            "w":6,
            "h":20,
            "minH":20,
            "minW":2
          },
          {
            "i":"chart",
            "x":6,
            "y":0,
            "w":6,
            "h":20,
            "minH":20,
            "minW":3
          },
          {
            "i":"chart-depth",
            "x":0,
            "y":1,
            "w":6,
            "h":20,
            "minH":10,
            "minW":1
          },
          {
            "i":"create-order",
            "x":6,
            "y":1,
            "w":6,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"orders",
            "x":0,
            "y":2,
            "w":6,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"account-summary",
            "x":6,
            "y":2,
            "w":6,
            "h":20,
            "minH":15,
            "minW":1
          },
          {
            "i":"positions",
            "x":0,
            "y":3,
            "w":12,
            "h":20,
            "minH":15,
            "minW":4
          }
        ],
        "xxs":[
          {
            "i":"history",
            "x":0,
            "y":0,
            "w":12,
            "h":20,
            "minH":20,
            "minW":2
          },
          {
            "i":"contract-details",
            "x":0,
            "y":7,
            "w":12,
            "h":20,
            "minW":2
          },
          {
            "i":"chart",
            "x":0,
            "y":1,
            "w":12,
            "h":20,
            "minH":20,
            "minW":3
          },
          {
            "i":"chart-depth",
            "x":0,
            "y":2,
            "w":12,
            "h":20,
            "minH":10,
            "minW":1
          },
          {
            "i":"create-order",
            "x":0,
            "y":3,
            "w":12,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"orders",
            "x":0,
            "y":4,
            "w":12,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"account-summary",
            "x":0,
            "y":5,
            "w":12,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"positions",
            "x":0,
            "y":6,
            "w":12,
            "h":20,
            "minH":15,
            "minW":4
          }
        ]
      },
      options_layouts: {
        "lg":[
          {
            "w":8,
            "h":60,
            "x":0,
            "y":0,
            "i":"board",
            "minW":4,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":60,
            "x":10,
            "y":0,
            "i":"create-order",
            "minW":2,
            "minH":20,
            "moved":false,
            "static":false
          },
          {
            "w":8,
            "h":30,
            "x":0,
            "y":60,
            "i":"positions",
            "minW":4,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":60,
            "x":8,
            "y":0,
            "i":"orders",
            "minW":2,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":30,
            "x":10,
            "y":60,
            "i":"account-summary",
            "minW":1,
            "minH":15,
            "moved":false,
            "static":false
          },
          {
            "w":2,
            "h":30,
            "x":8,
            "y":60,
            "i":"contract-details",
            "minW":2,
            "minH":20,
            "moved":false,
            "static":false
          }
        ],
        "md":[
          {
            "i":"board",
            "x":0,
            "y":0,
            "w":6,
            "h":20,
            "minH":15,
            "minW":4
          },
          {
            "i":"orders",
            "x":6,
            "y":0,
            "w":6,
            "h":20,
            "minH":15,
            "minW":2
          },
          {
            "i":"contract-details",
            "x":6,
            "y":2,
            "w":6,
            "h":20,
            "minH":20,
            "minW":2
          },
          {
            "i":"create-order",
            "x":0,
            "y":1,
            "w":6,
            "h":40,
            "minH":20,
            "minW":2
          },
          {
            "i":"account-summary",
            "x":6,
            "y":2,
            "w":6,
            "h":20,
            "minH":15,
            "minW":1
          },
          {
            "i":"positions",
            "x":0,
            "y":3,
            "w":12,
            "h":20,
            "minH":15,
            "minW":1
          }
        ],
        "xxs":[
          {
            "i":"board",
            "x":0,
            "y":0,
            "w":12,
            "h":20,
            "minH":15,
            "minW":4
          },
          {
            "i":"orders",
            "x":0,
            "y":1,
            "w":12,
            "h":20,
            "minH":15,
            "minW":2
          },
          {
            "i":"contract-details",
            "x":0,
            "y":4,
            "w":12,
            "h":20,
            "minH":20
          },
          {
            "i":"create-order",
            "x":0,
            "y":2,
            "w":12,
            "h":20,
            "minH":20,
            "minW":2
          },
          {
            "i":"account-summary",
            "x":0,
            "y":5,
            "w":12,
            "h":20,
            "minH":20,
            "minW":1
          },
          {
            "i":"positions",
            "x":0,
            "y":3,
            "w":12,
            "h":20,
            "minH":15,
            "minW":1
          }
        ]
      }
    },

    translations: {
      'en-US': {
        "accessLog.table.head.city": "city",
        "accessLog.table.head.country": "country",
        "accessLog.table.head.date": "date",
        "accessLog.table.head.ip": "IP",
        "accessLog.table.head.userAgent": "user agent",
        "account.card.accountId": "AccountID",
        "account.card.actions.info": "Info",
        "account.card.actions.trade": "Trade",
        "account.card.available": "Available",
        "account.card.processingFee": "Processing Fee",
        "account.card.totalBalance": "Total Balance",
        "account.card.type": "Type",
        "account.info.availableBalance": "Available balance",
        "account.info.availableWithdrawBalance": "Available withdraw balance",
        "account.info.balance": "Balance",
        "account.info.createdAt": "Created At",
        "account.info.currency": "Currency",
        "account.info.equity": "Equity",
        "account.info.initialMargin": "Initial margin",
        "account.info.maintenanceMargin": "Maintenance margin",
        "account.info.marginBalance": "Margin balance",
        "account.info.name": "Name",
        "account.info.orderInitialMargin": "Order initial margin",
        "account.info.unrealizedPl": "Unrealized PL",
        "account.info.updatedAt": "Updated At",
        "accountPage.title": "Trading account {id}",
        "accountSummaryBox.buttons.deposit": "DEPOSIT",
        "accountSummaryBox.buttons.withdraw": "WITHDRAW",
        "accountTrades.liquidity.liquidation": "Liquidation",
        "accountTrades.liquidity.maker": "Maker",
        "accountTrades.liquidity.taker": "Taker",
        "accountTrades.table.head.accountId": "Account ID",
        "accountTrades.table.head.createdAt": "Created At",
        "accountTrades.table.head.direction": "Direction",
        "accountTrades.table.head.fee": "Fee",
        "accountTrades.table.head.instrument": "Instrument",
        "accountTrades.table.head.liquidationFee": "Liquidation Fee",
        "accountTrades.table.head.liquidity": "Liquidity",
        "accountTrades.table.head.price": "Price",
        "accountTrades.table.head.sequenceNo": "SequenceNo",
        "accountTrades.table.head.size": "Size",
        "accountTrades.table.head.symbol": "Symbol",
        "accountTrades.table.head.time": "Time",
        "accountTrades.table.head.tradeId": "Trade ID",
        "accounts.list.head.availableBalance": "AVAILABLE BALANCE",
        "accounts.list.head.availableWithdrawBalance": "AVAILABLE WITHDRAW BALANCE",
        "accounts.list.head.balance": "BALANCE",
        "accounts.list.head.currency": "CURRENCY",
        "accounts.list.head.id": "ACCOUNT ID",
        "accounts.list.head.name": "NAME",
        "accounts.menu.accessLogs": "Access Log",
        "accounts.menu.account": "Account",
        "accounts.menu.accounts": "Trading Accounts",
        "accounts.menu.apiLKeys": "Api keys",
        "accounts.menu.apiTokens": "API Tokens",
        "accounts.menu.deposit": "Deposit",
        "accounts.menu.deposits": "Deposits",
        "accounts.menu.orders": "Orders",
        "accounts.menu.positions": "Positions",
        "accounts.menu.profile": "Profile",
        "accounts.menu.settings": "Settings",
        "accounts.menu.trades": "Trades",
        "accounts.menu.tradingAccounts": "Trading Accounts",
        "accounts.menu.transactions": "Transactions",
        "accounts.menu.transfer": "Transfer",
        "accounts.menu.verification": "Verification",
        "accounts.menu.withdrawal": "Withdrawal",
        "accounts.menu.withdrawals": "Withdrawals",
        "actualStat.24hChange": "24h change",
        "actualStat.fundingIn": "Funding in",
        "actualStat.lastPrice": "Last price",
        "actualStat.turnover": "Turnover",
        "actualStat.volume": "Volume",
        "apiKeys.table.head.actions": "Actions",
        "apiKeys.table.head.createdAt": "Created AT",
        "apiKeys.table.head.id": "ID",
        "apiKeys.table.head.scopes": "scopes",
        "app.header.title": "Trading Platform",
        "appMenu.account": "Account",
        "appMenu.reference": "Reference",
        "appMenu.trade": "Terminal",
        "changePasswordForm.button.submit": "Save",
        "changePasswordForm.currentPassword.error.required": "Please input your Current Password!",
        "changePasswordForm.currentPassword.placeholder": "Current Password",
        "changePasswordForm.newPassword.error.required": "Please input your New Password!",
        "changePasswordForm.newPassword.placeholder": "New Password",
        "changePasswordForm.repeatPassword.error.notMatch": "The two passwords that you entered do not match!",
        "changePasswordForm.repeatPassword.error.required": "Please repeat your New Password!",
        "changePasswordForm.repeatPassword.placeholder": "Repeat Password",
        "changePasswordForm.title": "Change Password",
        "common.buttons.cancelApiToken": "Cancel",
        "common.buttons.cancelOrder": "Cancel",
        "common.buttons.cancelWithdrawal": "Cancel",
        "common.buttons.copied": "COPIED",
        "common.buttons.copy": "COPY",
        "common.buttons.createApiToken": "Create API token",
        "common.buttons.depositFunds": "Deposit Funds",
        "common.buttons.disableMfa": "Disable 2FA",
        "common.buttons.editAccount": "Edit Account",
        "common.buttons.editTokenPermissions": "Edit Token Permissions",
        "common.buttons.exportToCsv": "Export to CSV",
        "common.buttons.goBack": "Back",
        "common.buttons.login": "Login",
        "common.buttons.logout": "Logout",
        "common.buttons.newAccount": "Create account",
        "common.buttons.signIn": "Signin",
        "common.buttons.signUp": "Signup",
        "common.buttons.transferFunds": "Transfer Funds",
        "common.buttons.withdrawFunds": "Withdraw Funds",
        "common.error.passwordValidation": "The password should be at least {minLength} symbols and contain letters and numbers",
        "common.na": "NA",
        "common.pageNotFoundMessage": "Sorry, this page was not found",
        "common.permissions.read": "Read",
        "common.permissions.write": "Write",
        "common.selectAccount.accountPrefix": "Account",
        "common.selectAccount.placeholder": "Select account",
        "common.table.noData": "No Data",
        "common.table.pagination.buttons.nextPage": "Next",
        "common.table.pagination.buttons.prevPage": "Previous",
        "common.table.pagination.found": "Showing {indexFrom} to {indexTo} of {totalCount} elements",
        "common.table.settings.columns": "Show/Hide Columns",
        "common.table.settings.label": "Settings",
        "common.table.settings.pageSize": "Page Size",
        "common.table.settings.reset": "Reset",
        "dataTable.filters.reset": "Reset",
        "dataTable.filters.search": "Search",
        "dataTable.filters.searchBy": "Search by",
        "deposits.table.head.accountId": "Account ID",
        "deposits.table.head.address": "Address",
        "deposits.table.head.amount": "Amount",
        "deposits.table.head.createdAt": "created At",
        "deposits.table.head.currency": "Currency",
        "deposits.table.head.depositId": "Deposit ID",
        "deposits.table.head.networkFee": "Network Fee",
        "deposits.table.head.state": "State",
        "deposits.table.head.teDepositId": "TE Deposit ID",
        "deposits.table.head.txId": "Tx ID",
        "deposits.table.head.userId": "User ID",
        "deposits.table.head.vOut": "V Out",
        "depthChart.labels.ask": "Ask",
        "depthChart.labels.bid": "Bid",
        "depthChart.tooltip.beforeLabel": "Current: {value}",
        "depthChart.tooltip.label": "Total: {value}",
        "depthChart.tooltip.title": "Price: {value}",
        "duration.days": "{days} {days, plural, one {day} other {days}}",
        "duration.hours": "{hours} {hours, plural, one {hour} other {hours}}",
        "forms.completePasswordRecovery.buttons.submit": "Save Password",
        "forms.completePasswordRecovery.title": "Complete Recovery",
        "forms.completeSignUp.buttons.submit": "Create Account",
        "forms.completeSignUp.title": "Complete Signup",
        "forms.newPassword.password.errors.required": "Please input your Password!",
        "forms.newPassword.password.placeholder": "Password",
        "forms.newPassword.repeatPassword.errors.notEqual": "The two passwords that you entered do not match!",
        "forms.newPassword.repeatPassword.errors.required": "Please confirm your Password!",
        "forms.repeatPassword.password.placeholder": "Repeat Password",
        "forms.signIn.buttons.Signup": "Signup",
        "forms.signIn.buttons.forgotPassword": "Forgot password",
        "forms.signIn.buttons.submit": "Submit",
        "forms.signIn.email.error.required": "Please input your Email Address!",
        "forms.signIn.email.placeholder": "Email Address",
        "forms.signIn.password.error.required": "Please input your Password!",
        "forms.signIn.password.placeholder": "Password",
        "forms.signIn.remember": "Keep me signed in",
        "forms.signIn.terms": "I accept the <TermsLink>terms and conditions</TermsLink>",
        "forms.signIn.title": "Signin",
        "forms.signUp.buttons.forgotPassword": "Forgot password",
        "forms.signUp.buttons.signIn": "Login",
        "forms.signUp.buttons.submit": "Create Account",
        "forms.signUp.email.error.required": "Please input your Email Address!",
        "forms.signUp.isTaxResidentAccepted.error.required": "Please accept you aren't a U.S. tax resident!",
        "forms.signUp.isTaxResidentAccepted.label": "I'm not a U.S. tax resident",
        "forms.signUp.isTermsAccepted.error.required": "Please accept <TermsLink>terms and conditions</TermsLink>!",
        "forms.signUp.isTermsAccepted.label": "I accept the <TermsLink>terms and conditions</TermsLink>",
        "forms.signUp.title": "Signup",
        "funding.menu.title": "Funding",
        "funding.table.head.funding_rate": "Funding Rate",
        "funding.table.head.funding_rate_daily": "Funding Rate Daily",
        "funding.table.head.interval": "Funding Interval",
        "funding.table.head.symbol": "Symbol",
        "funding.table.head.timestamp": "Timestamp",
        "instrument.fields.baseIm": "Base Initial Margin",
        "instrument.fields.baseMm": "Base Maintenance Margin",
        "instrument.fields.contractSize": "Contract Size",
        "instrument.fields.contractType": "Contract Type",
        "instrument.fields.deliveryAt": "Delivery Date",
        "instrument.fields.deliveryFee": "Delivery Fee",
        "instrument.fields.deliveryFeeCap": "Delivery Fee Cap",
        "instrument.fields.deliveryIndex": "Delivery Index",
        "instrument.fields.expirationAt": "Expiration Date",
        "instrument.fields.fairPriceImpactClamp": "Fair Price Clamp",
        "instrument.fields.fairPriceImpactDepth": "Fair Price Impact Depth",
        "instrument.fields.fundingInterval": "Funding Interval",
        "instrument.fields.fundingReferenceAt": "Funding Times",
        "instrument.fields.fundingSymbol": "Funding Index",
        "instrument.fields.incrementalM": "Incremental Margin",
        "instrument.fields.liquidationExchangeFee": "Liquidation Exchange Fee",
        "instrument.fields.liquidationExchangeFeeCap": "Liquidation Exchange Fee Cap",
        "instrument.fields.liquidationInsuranceFee": "Liquidation Insurance Fee",
        "instrument.fields.liquidationInsuranceFeeCap": "Liquidation Insurance Fee Cap",
        "instrument.fields.listedAt": "List Date",
        "instrument.fields.makerFee": "Maker Fee",
        "instrument.fields.makerFeeCap": "Maker Fee Cap",
        "instrument.fields.markIndex": "Mark Index",
        "instrument.fields.maxOrderQty": "Max Order Quantity",
        "instrument.fields.maxPositionSize": "Max Position Size",
        "instrument.fields.maxPrice": "Max Price",
        "instrument.fields.maxTradeSize": "Max Trade Size",
        "instrument.fields.minPrice": "Min Price",
        "instrument.fields.minTradeAmount": "Min Trade Amount",
        "instrument.fields.referenceIndex": "Reference Index",
        "instrument.fields.riskStep": "Risk Step",
        "instrument.fields.symbol": "Symbol",
        "instrument.fields.takerFee": "Taker Fee",
        "instrument.fields.takerFeeCap": "Taker Fee Cap",
        "instrument.fields.tickSize": "Tick Size",
        "instrument.type.future": "Future",
        "instrument.type.option": "Option",
        "instrument.type.perpetual": "Perpetual",
        "insurance.menu.title": "Insurance",
        "insurance.table.head.balance": "Balance",
        "insurance.table.head.currency": "Currency",
        "insurance.table.head.timestamp": "Timestamp",
        "modals.accessTokensConfirmation.id": "ID:",
        "modals.accessTokensConfirmation.secret": "Secret:",
        "modals.activateMfa.agreement": "I have saved the above code",
        "modals.activateMfa.buttons.submit": "Enable 2FA",
        "modals.activateMfa.text": "Download Google Authenticator, scan the QR code below and store the code offline",
        "modals.activateMfa.title": "Activate 2FA",
        "modals.amendOrder.buttons.amend": "Amend",
        "modals.amendOrder.title": "Amend Order",
        "modals.common.buttons.cancel": "Cancel",
        "modals.confirmation.buttons.resendEmail": "Resend Email",
        "modals.depositFunds.account.errors.required": "Please select your Account!",
        "modals.depositFunds.address": "Deposit address",
        "modals.depositFunds.buttons.submit": "Submit",
        "modals.depositFunds.message": "Do not send Litecoin, Bitcoin Cash, or Tether to this address!",
        "modals.depositFunds.title": "Deposit Funds",
        "modals.disableMfa.title": "Disable 2FA",
        "modals.editAccount.buttons.save": "Save",
        "modals.editAccount.currency.errors.required": "Please input your Currency!",
        "modals.editAccount.currency.placeholder": "Currency",
        "modals.editAccount.isDefault": "Primary (default) wallet",
        "modals.editAccount.name.errors.required": "Please input your Name!",
        "modals.editAccount.name.placeholder": "Alias Name",
        "modals.editAccount.title": "Edit Account",
        "modals.editTokenPermissions.account": "Account",
        "modals.editTokenPermissions.blockTrade": "Block Trade",
        "modals.editTokenPermissions.buttons.save": "Save Permissions",
        "modals.editTokenPermissions.status": "Status",
        "modals.editTokenPermissions.status.active": "Active",
        "modals.editTokenPermissions.title": "Edit Token Permissions",
        "modals.editTokenPermissions.trade": "Trade",
        "modals.editTokenPermissions.wallet": "Wallet",
        "modals.emailConfirmation.line1": "Please be patient",
        "modals.emailConfirmation.line2": "as it may require more",
        "modals.emailConfirmation.line3": "than a couple of minutes to delivery",
        "modals.emailConfirmation.title": "Email Confirmation",
        "modals.mfaInput.buttons.submit": "Submit",
        "modals.mfaInput.message": "An email has been sent to your inbox with a 6 digit code.",
        "modals.mfaInput.title": "2FA Authorisation",
        "modals.mfaReminder.buttons.enable": "Enable 2FA",
        "modals.mfaReminder.buttons.skip": "Skip",
        "modals.mfaReminder.message": "Download Google Authenticator, scan the QR code below and store the code offline",
        "modals.mfaReminder.title": "Reminder: Activate 2FA",
        "modals.newAccount.buttons.createAccount": "Create Account",
        "modals.newAccount.title": "New Account",
        "modals.orderApproval.availableBalance": "Available",
        "modals.orderApproval.buttons.submit": "Place Order",
        "modals.orderApproval.limitPrice": "Limit Price",
        "modals.orderApproval.markPrice": "Mark Price",
        "modals.orderApproval.orderSize": "Amount",
        "modals.orderApproval.takeProfitStopLoss": "Take profit/Stop loss",
        "modals.orderApproval.takeProfitStopLoss.notEnabled": "Not Enabled",
        "modals.orderApproval.title": "Order Approval",
        "modals.recoveryPasswordConfirmation.line1": "An email has been sent to your inbox",
        "modals.recoveryPasswordConfirmation.line2": "with a password recovery link.",
        "modals.recoveryPasswordConfirmation.line3": "Click on the link and change your password.",
        "modals.recoveryPasswordConfirmation.title": "Recovery Link",
        "modals.transferApproval.amount": "Amount",
        "modals.transferApproval.buttons.submit": "Approve",
        "modals.transferApproval.fromAccount": "From Account",
        "modals.transferApproval.title": "Transfer Approval",
        "modals.transferApproval.toAccount": "To Account",
        "modals.transferFunds.accountPrefix.source": "Source Account ",
        "modals.transferFunds.accountPrefix.target": "Target Account ",
        "modals.transferFunds.amount.errors.required": "Please set Amount!",
        "modals.transferFunds.amount.placeholder": "Amount",
        "modals.transferFunds.buttons.submit": "Transfer",
        "modals.transferFunds.buttons.useMax": "USE MAX",
        "modals.transferFunds.fromAccountId.errors.required": "Please select source Account!",
        "modals.transferFunds.fromAccountId.placeholder": "Select source account",
        "modals.transferFunds.title": "Transfer Funds",
        "modals.transferFunds.toAccountId.errors.required": "Please select target Account!",
        "modals.transferFunds.toAccountId.placeholder": "Select target account",
        "modals.withdrawFunds.accountId.error.required": "Please input your Account!",
        "modals.withdrawFunds.amount.error.required": "Please input your Amount!",
        "modals.withdrawFunds.amount.placeholder": "Amount",
        "modals.withdrawFunds.amount.useBaxBtn": "USE MAX",
        "modals.withdrawFunds.buttons.submit": "Withdraw",
        "modals.withdrawFunds.destAddress.error.required": "Please input your Destination Address!",
        "modals.withdrawFunds.destAddress.placeholder": "Destination Address",
        "modals.withdrawFunds.minWithdrawal": "Minimum available withdrawal is ",
        "modals.withdrawFunds.networkFee.error.minValue": "Min value is {value}",
        "modals.withdrawFunds.networkFee.error.required": "Please input your Fee!",
        "modals.withdrawFunds.networkFee.placeholder": "Network Fee",
        "modals.withdrawFunds.title": "Withdraw Funds",
        "modals.withdrawalApproval.account": "Account",
        "modals.withdrawalApproval.address": "Address",
        "modals.withdrawalApproval.amount": "Amount",
        "modals.withdrawalApproval.buttons.submit": "Approve",
        "modals.withdrawalApproval.networkFee": "Network Fee",
        "modals.withdrawalApproval.title": "Withdrawal Approval",
        "modals.withdrawalConfirmation.text": "Please be patient as it may require more than a couple of minutes to delivery",
        "modals.withdrawalConfirmation.title": "Withdrawal Confirmed",
        "notifications.apiKeyCreated": "API key created successfully",
        "notifications.apiKeyRemoved": "API token was removed successfully",
        "notifications.error.orderCanceled": "Order canceled",
        "notifications.error.transferError": "Something goes wrong with transfer",
        "notifications.errors.somethingGoesWrong": "Something goes wrong",
        "notifications.mfaEnabled": "Enabled MFA authentication!",
        "notifications.orderUpdated": "Order updated",
        "notifications.passwordChanged": "Password changed",
        "notifications.transferCreated": "Transfer created!",
        "notifications.withdrawCancelled": "Withdraw was cancelled successfully",
        "notifications.withdrawConfirmed": "Withdraw confirmed!",
        "notifications.withdrawalCreated": "Withdrawal created",
        "options.greek.gamma": "Gamma",
        "options.greek.theta": "Theta",
        "options.greek.vega": "Vega",
        "options.table.head.ask": "Ask",
        "options.table.head.bid": "Bid",
        "options.table.head.delta": "âˆ† Delta",
        "options.table.head.iv": "IV",
        "options.table.head.last": "Last",
        "options.table.head.mark": "Mark",
        "options.table.head.open": "Open",
        "options.table.head.pos": "Pos",
        "options.table.head.size": "Size",
        "options.table.head.strike": "Strike",
        "options.table.head.vol": "Vol",
        "order.actions.amend": "Amend",
        "order.create.advanced": "Advanced",
        "order.create.amount.label": "Amount",
        "order.create.amount.placeholder": "Amount",
        "order.create.available": "Available",
        "order.create.buttons.buy": "BUY ORDER",
        "order.create.buttons.sell": "SELL ORDER",
        "order.create.hiddenQty": "Hidden Qty",
        "order.create.initialMargin": "Initial Margin",
        "order.create.notification.error": "Creating order error",
        "order.create.notification.success": "Order created",
        "order.create.postOnly": "Post Only",
        "order.create.price.label": "Limit Price",
        "order.create.price.placeholder": "Limit Price",
        "order.create.reduceOnly": "Reduce Only",
        "order.create.stopLoss": "Stop Loss",
        "order.create.takeProfit": "Take Profit",
        "order.create.triggerPrice.items.index": "Index",
        "order.create.triggerPrice.items.last": "Last",
        "order.create.triggerPrice.items.mark": "Mark",
        "order.create.triggerPrice.placeholder": "Trigger Price",
        "order.side.buy": "Long (Buy)",
        "order.side.sell": "Sell (Short)",
        "order.timeInForce.fok": "Fill or Kill",
        "order.timeInForce.gtc": "Good 'Til Cancel",
        "order.timeInForce.ioc": "Immediate or Cancel",
        "orderBook.head.priceUsd": "Price (USD)",
        "orderBook.head.size": "Size",
        "orderBook.head.total": "Total",
        "orderBook.tooltip.avgPrice": "Avg. Price",
        "orderBook.tooltip.sumSize": "Sum. Size",
        "orderBook.tooltip.sumTotal": "Sum. Total",
        "ordersTable.head.accountId": "Account id",
        "ordersTable.head.action": "Action",
        "ordersTable.head.actions": "Actions",
        "ordersTable.head.avgPrice": "Avg.Price",
        "ordersTable.head.displaySize": "Display Size",
        "ordersTable.head.fillSize": "Fill Size",
        "ordersTable.head.filledSize": "Filled Size",
        "ordersTable.head.filledSizeCurrency": "Filled Size Currency",
        "ordersTable.head.instrument": "Instrument",
        "ordersTable.head.label": "Label",
        "ordersTable.head.orderId": "Order id",
        "ordersTable.head.position": "Position",
        "ordersTable.head.postReduceOnly": "Post / Reduce only",
        "ordersTable.head.price": "Price",
        "ordersTable.head.remainingSize": "Remaining Size",
        "ordersTable.head.side": "Side",
        "ordersTable.head.size": "Size",
        "ordersTable.head.status": "Status",
        "ordersTable.head.symbol": "Symbol",
        "ordersTable.head.time": "Time",
        "ordersTable.head.type": "Type",
        "overlays.signUpInvite.line1": "Please <LoginLink>Login</LoginLink> or <SignUpLink>Signup</SignUpLink>",
        "overlays.signUpInvite.line2": "to Trade",
        "passwordRecovery.buttons.submit": "Submit",
        "passwordRecovery.email.error.required": "Please input your Email Address!",
        "passwordRecovery.email.placeholder": "Email Address",
        "passwordRecovery.title": "Password Recovery",
        "positionPage.title": "Position {id}",
        "positions.actions.actions.closePrice": "Close",
        "positions.actions.actions.closePrice.input.placeholder": "Close Price",
        "positions.actions.market": "Market",
        "positionsTable.head.action": "Action",
        "positionsTable.head.avgPrice": "Avg. Price",
        "positionsTable.head.currency": "Currency",
        "positionsTable.head.estLiqPrice": "Est. Liq. Price",
        "positionsTable.head.initMargin": "Init. Margin",
        "positionsTable.head.initialMargin": "Initial Margin",
        "positionsTable.head.instrument": "Instrument",
        "positionsTable.head.maintMargin": "Maint Margin",
        "positionsTable.head.markPrice": "Mark Price",
        "positionsTable.head.positionId": "Position ID",
        "positionsTable.head.realisedPnlRoe": "Realised PNL (ROE %)",
        "positionsTable.head.realizedPl": "Realized Pl.",
        "positionsTable.head.side": "Side",
        "positionsTable.head.size": "Size",
        "positionsTable.head.sizeCurrency": "Size Currency",
        "positionsTable.head.symbol": "Symbol",
        "positionsTable.head.type": "Type",
        "positionsTable.head.unrealisedPnlRoe": "Unrealised PNL (ROE %)",
        "profile.cards.2fa": "2FA",
        "profile.cards.2faDescription": "Two-factor Authentication adds an extra layer of security to your account by asking for a verification code when you sign in\n",
        "profile.cards.accountId": "Account ID",
        "profile.cards.accountSettings": "Account Settings",
        "profile.cards.accountSettings.changePassword": "Change Password",
        "profile.cards.displayMode": "Display Mode",
        "profile.cards.email": "Email",
        "profile.cards.language": "Language",
        "profile.cards.password": "Password",
        "profile.cards.preferences": "Preferences",
        "profile.header": "Profile",
        "publicTrades.table.head.price": "Price (USD)",
        "publicTrades.table.head.size": "Size",
        "publicTrades.table.head.time": "Time",
        "references.indices.breakdown": "Historical Composite Breakdown",
        "references.instrument.specification.delivery": "Delivery",
        "references.instrument.specification.fees": "Fees",
        "references.instrument.specification.funding": "Funding",
        "references.instrument.specification.mark": "Mark Index and Pricing",
        "references.instrument.specification.riskLimit": "Risk Limits and Margin",
        "references.menu.api": "API Explorer",
        "references.menu.contracts": "Contracts",
        "references.menu.funding": "Funding",
        "references.menu.indices": "Indices",
        "references.menu.instrument.overview": "Overview",
        "references.menu.instrument.specification": "Specification",
        "references.menu.insurance": "Insurance",
        "references.menu.settlement": "Settlement",
        "selectInstrument.table.head.expiry": "Expiry",
        "selectInstrument.table.head.lastPrice": "Last Price",
        "selectInstrument.table.head.symbol": "Symbol",
        "selectInstrument.table.head.type": "Type",
        "settlement.menu.title": "Settlement",
        "settlement.table.head.createdAt": "Created At",
        "settlement.table.head.markPrice": "Mark Price",
        "settlement.table.head.price": "Price",
        "settlement.table.head.strike_price": "Strike Price",
        "settlement.table.head.symbol": "Symbol",
        "settlement.table.head.timestamp": "Timestamp",
        "settlement.table.head.type": "type",
        "settlement.table.head.updatedAt": "Updated At",
        "statusBar.status.error": "Partially active or something",
        "statusBar.status.ok": "All systems operational",
        "symbol.breakdown.list.head.ask": "Ask",
        "symbol.breakdown.list.head.bid": "Bid",
        "symbol.breakdown.list.head.provider": "Provider",
        "symbol.breakdown.list.head.time": "Time",
        "symbol.breakdown.list.head.type": "Type",
        "symbol.breakdown.list.head.weight": "Weight",
        "taskbar.setting": "Settings",
        "taskbar.setting.items.darkTheme": "Dark theme",
        "taskbar.setting.items.resetLayouts": "Reset layouts to default",
        "transactions.table.head.action": "action",
        "transactions.table.head.baseCashflow": "base_cashflow",
        "transactions.table.head.cashflow": "cashflow",
        "transactions.table.head.createdAt": "created at",
        "transactions.table.head.currency": "currency",
        "transactions.table.head.description": "description",
        "transactions.table.head.fee": "fee",
        "transactions.table.head.id": "ID",
        "transactions.table.head.insuranceFee": "insurance_fee",
        "transactions.table.head.symbol": "symbol",
        "transactions.table.head.type": "Type",
        "transactions.title.deposits": "Deposits",
        "transactions.title.referralsIn": "Referrals In",
        "transactions.title.referralsOut": "Referrals Out",
        "transactions.title.transactions": "Transactions",
        "transactions.title.transfersIn": "Transfers In",
        "transactions.title.transfersOut": "Transfers Out",
        "transactions.title.withdrawals": "Withdrawals",
        "userMenu.items.accounts": "Trading Accounts",
        "userMenu.items.deposit": "Deposit",
        "userMenu.items.settings": "Settings",
        "userMenu.menu.transfer": "Transfer",
        "userMenu.menu.withdrawal": "Withdrawal",
        "verification.table.head.fileName": "File Name",
        "wallet.menu.title": "Wallets",
        "wallet.table.head.id": "id",
        "widget.indicator.groups.createOrder": "Create Order",
        "widget.indicator.groups.private": "Private",
        "widget.indicator.groups.public": "Public",
        "widget.indicator.newForm.account": "Account",
        "widget.indicator.newForm.account.placeholder": "Use the current account",
        "widget.indicator.newForm.buttons.create": "Add Indicator",
        "widget.indicator.newForm.indicator": "Indicator",
        "widget.indicator.newForm.indicator.error": "Please specify the indicator first",
        "widget.indicator.newForm.instrument": "Instrument",
        "widget.indicator.newForm.instrument.placeholder": "Use the navigation one",
        "widget.indicator.title.accountSummary": "Account Summary",
        "widget.indicator.title.accountTrades": "Trade History",
        "widget.indicator.title.chart": "Chart",
        "widget.indicator.title.chartDepths": "Chart Depths",
        "widget.indicator.title.closedOrders": "Order History",
        "widget.indicator.title.contractDetails": "Contract Details",
        "widget.indicator.title.createLimitOrder": "LIMIT",
        "widget.indicator.title.createMarketOrder": "MARKET",
        "widget.indicator.title.new": "New",
        "widget.indicator.title.openOrders": "Open Orders",
        "widget.indicator.title.optionsBoard": "Options Board",
        "widget.indicator.title.orderBook": "Order Book",
        "widget.indicator.title.positions": "Positions",
        "widget.indicator.title.publicTrades": "Trade History",
        "withdrawals.table.head.accountId": "Account Id",
        "withdrawals.table.head.actions": "Actions",
        "withdrawals.table.head.address": "Address",
        "withdrawals.table.head.amount": "amount",
        "withdrawals.table.head.createdAt": "created At",
        "withdrawals.table.head.networkFee": "network fee",
        "withdrawals.table.head.state": "state",
        "withdrawals.table.head.transactionId": "Transaction ID",
        "withdrawals.table.head.vOut": "v_out",
        "withdrawals.table.head.withdrawId": "Withdraw ID"
      },
      'ru-RU': {
        "accessLog.table.head.city": "city",
        "accessLog.table.head.country": "country",
        "accessLog.table.head.date": "date",
        "accessLog.table.head.ip": "IP",
        "accessLog.table.head.userAgent": "user agent",
        "account.card.accountId": "AccountID",
        "account.card.actions.info": "Info",
        "account.card.actions.trade": "Trade",
        "account.card.available": "Available",
        "account.card.processingFee": "Processing Fee",
        "account.card.totalBalance": "Total Balance",
        "account.card.type": "Type",
        "account.info.availableBalance": "Available balance",
        "account.info.availableWithdrawBalance": "Available withdraw balance",
        "account.info.balance": "Balance",
        "account.info.createdAt": "Created At",
        "account.info.currency": "Currency",
        "account.info.equity": "Equity",
        "account.info.initialMargin": "Initial margin",
        "account.info.maintenanceMargin": "Maintenance margin",
        "account.info.marginBalance": "Margin balance",
        "account.info.name": "Name",
        "account.info.orderInitialMargin": "Order initial margin",
        "account.info.unrealizedPl": "Unrealized PL",
        "account.info.updatedAt": "Updated At",
        "accountPage.title": "Trading account {id}",
        "accountSummaryBox.buttons.deposit": "DEPOSIT",
        "accountSummaryBox.buttons.withdraw": "WITHDRAW",
        "accountTrades.liquidity.liquidation": "Liquidation",
        "accountTrades.liquidity.maker": "Maker",
        "accountTrades.liquidity.taker": "Taker",
        "accountTrades.table.head.accountId": "Account ID",
        "accountTrades.table.head.createdAt": "Created At",
        "accountTrades.table.head.direction": "Direction",
        "accountTrades.table.head.fee": "Fee",
        "accountTrades.table.head.instrument": "Instrument",
        "accountTrades.table.head.liquidationFee": "Liquidation Fee",
        "accountTrades.table.head.liquidity": "Liquidity",
        "accountTrades.table.head.price": "Price",
        "accountTrades.table.head.sequenceNo": "SequenceNo",
        "accountTrades.table.head.size": "Size",
        "accountTrades.table.head.symbol": "Symbol",
        "accountTrades.table.head.time": "Time",
        "accountTrades.table.head.tradeId": "Trade ID",
        "accounts.list.head.availableBalance": "AVAILABLE BALANCE",
        "accounts.list.head.availableWithdrawBalance": "AVAILABLE WITHDRAW BALANCE",
        "accounts.list.head.balance": "BALANCE",
        "accounts.list.head.currency": "CURRENCY",
        "accounts.list.head.id": "ACCOUNT ID",
        "accounts.list.head.name": "NAME",
        "accounts.menu.accessLogs": "Access Log",
        "accounts.menu.account": "Account",
        "accounts.menu.accounts": "Trading Accounts",
        "accounts.menu.apiLKeys": "Api keys",
        "accounts.menu.apiTokens": "API Tokens",
        "accounts.menu.deposit": "Deposit",
        "accounts.menu.deposits": "Deposits",
        "accounts.menu.orders": "Orders",
        "accounts.menu.positions": "Positions",
        "accounts.menu.profile": "Profile",
        "accounts.menu.settings": "Settings",
        "accounts.menu.trades": "Trades",
        "accounts.menu.tradingAccounts": "Trading Accounts",
        "accounts.menu.transactions": "Transactions",
        "accounts.menu.transfer": "Transfer",
        "accounts.menu.verification": "Verification",
        "accounts.menu.withdrawal": "Withdrawal",
        "accounts.menu.withdrawals": "Withdrawals",
        "actualStat.24hChange": "24h change",
        "actualStat.fundingIn": "Funding in",
        "actualStat.lastPrice": "Last price",
        "actualStat.turnover": "Turnover",
        "actualStat.volume": "Volume",
        "apiKeys.table.head.actions": "Actions",
        "apiKeys.table.head.createdAt": "Created AT",
        "apiKeys.table.head.id": "ID",
        "apiKeys.table.head.scopes": "scopes",
        "app.header.title": "Trading Platform",
        "appMenu.account": "Account",
        "appMenu.reference": "Reference",
        "appMenu.trade": "Terminal",
        "changePasswordForm.button.submit": "Save",
        "changePasswordForm.currentPassword.error.required": "Please input your Current Password!",
        "changePasswordForm.currentPassword.placeholder": "Current Password",
        "changePasswordForm.newPassword.error.required": "Please input your New Password!",
        "changePasswordForm.newPassword.placeholder": "New Password",
        "changePasswordForm.repeatPassword.error.notMatch": "The two passwords that you entered do not match!",
        "changePasswordForm.repeatPassword.error.required": "Please repeat your New Password!",
        "changePasswordForm.repeatPassword.placeholder": "Repeat Password",
        "changePasswordForm.title": "Change Password",
        "common.buttons.cancelApiToken": "Cancel",
        "common.buttons.cancelOrder": "Cancel",
        "common.buttons.cancelWithdrawal": "Cancel",
        "common.buttons.copied": "COPIED",
        "common.buttons.copy": "COPY",
        "common.buttons.createApiToken": "Create API token",
        "common.buttons.depositFunds": "Deposit Funds",
        "common.buttons.disableMfa": "Disable 2FA",
        "common.buttons.editAccount": "Edit Account",
        "common.buttons.editTokenPermissions": "Edit Token Permissions",
        "common.buttons.exportToCsv": "Export to CSV",
        "common.buttons.goBack": "Back",
        "common.buttons.login": "Login",
        "common.buttons.logout": "Logout",
        "common.buttons.newAccount": "Create account",
        "common.buttons.signIn": "Signin",
        "common.buttons.signUp": "Signup",
        "common.buttons.transferFunds": "Transfer Funds",
        "common.buttons.withdrawFunds": "Withdraw Funds",
        "common.error.passwordValidation": "The password should be at least {minLength} symbols and contain letters and numbers",
        "common.na": "NA",
        "common.pageNotFoundMessage": "Sorry, this page was not found",
        "common.permissions.read": "Read",
        "common.permissions.write": "Write",
        "common.selectAccount.accountPrefix": "Account",
        "common.selectAccount.placeholder": "Select account",
        "common.table.noData": "No Data",
        "common.table.pagination.buttons.nextPage": "Next",
        "common.table.pagination.buttons.prevPage": "Previous",
        "common.table.pagination.found": "Showing {indexFrom} to {indexTo} of {totalCount} elements",
        "common.table.settings.columns": "Show/Hide Columns",
        "common.table.settings.label": "Settings",
        "common.table.settings.pageSize": "Page Size",
        "common.table.settings.reset": "Reset",
        "dataTable.filters.reset": "Reset",
        "dataTable.filters.search": "Search",
        "dataTable.filters.searchBy": "Search by",
        "deposits.table.head.accountId": "Account ID",
        "deposits.table.head.address": "Address",
        "deposits.table.head.amount": "Amount",
        "deposits.table.head.createdAt": "created At",
        "deposits.table.head.currency": "Currency",
        "deposits.table.head.depositId": "Deposit ID",
        "deposits.table.head.networkFee": "Network Fee",
        "deposits.table.head.state": "State",
        "deposits.table.head.teDepositId": "TE Deposit ID",
        "deposits.table.head.txId": "Tx ID",
        "deposits.table.head.userId": "User ID",
        "deposits.table.head.vOut": "V Out",
        "depthChart.labels.ask": "Ask",
        "depthChart.labels.bid": "Bid",
        "depthChart.tooltip.beforeLabel": "Current: {value}",
        "depthChart.tooltip.label": "Total: {value}",
        "depthChart.tooltip.title": "Price: {value}",
        "duration.days": "{days} {days, plural, one {day} other {days}}",
        "duration.hours": "{hours} {hours, plural, one {hour} other {hours}}",
        "forms.completePasswordRecovery.buttons.submit": "Save Password",
        "forms.completePasswordRecovery.title": "Complete Recovery",
        "forms.completeSignUp.buttons.submit": "Create Account",
        "forms.completeSignUp.title": "Complete Signup",
        "forms.newPassword.password.errors.required": "Please input your Password!",
        "forms.newPassword.password.placeholder": "Password",
        "forms.newPassword.repeatPassword.errors.notEqual": "The two passwords that you entered do not match!",
        "forms.newPassword.repeatPassword.errors.required": "Please confirm your Password!",
        "forms.repeatPassword.password.placeholder": "Repeat Password",
        "forms.signIn.buttons.Signup": "Signup",
        "forms.signIn.buttons.forgotPassword": "Forgot password",
        "forms.signIn.buttons.submit": "Submit",
        "forms.signIn.email.error.required": "Please input your Email Address!",
        "forms.signIn.email.placeholder": "Email Address",
        "forms.signIn.password.error.required": "Please input your Password!",
        "forms.signIn.password.placeholder": "Password",
        "forms.signIn.remember": "Keep me signed in",
        "forms.signIn.terms": "I accept the <TermsLink>terms and conditions</TermsLink>",
        "forms.signIn.title": "Signin",
        "forms.signUp.buttons.forgotPassword": "Forgot password",
        "forms.signUp.buttons.signIn": "Login",
        "forms.signUp.buttons.submit": "Create Account",
        "forms.signUp.email.error.required": "Please input your Email Address!",
        "forms.signUp.isTaxResidentAccepted.error.required": "Please accept you aren't a U.S. tax resident!",
        "forms.signUp.isTaxResidentAccepted.label": "I'm not a U.S. tax resident",
        "forms.signUp.isTermsAccepted.error.required": "Please accept terms and conditions!",
        "forms.signUp.isTermsAccepted.label": "I accept the terms and conditions",
        "forms.signUp.title": "Signup",
        "funding.menu.title": "Funding",
        "funding.table.head.funding_rate": "Funding Rate",
        "funding.table.head.funding_rate_daily": "Funding Rate Daily",
        "funding.table.head.interval": "Funding Interval",
        "funding.table.head.symbol": "Symbol",
        "funding.table.head.timestamp": "Timestamp",
        "instrument.fields.baseIm": "Base Initial Margin",
        "instrument.fields.baseMm": "Base Maintenance Margin",
        "instrument.fields.contractSize": "Размер контракта",
        "instrument.fields.contractType": "Contract Type",
        "instrument.fields.deliveryAt": "Delivery Date",
        "instrument.fields.deliveryFee": "Delivery Fee",
        "instrument.fields.deliveryFeeCap": "Delivery Fee Cap",
        "instrument.fields.deliveryIndex": "Delivery Index",
        "instrument.fields.expirationAt": "Expiration Date",
        "instrument.fields.fairPriceImpactClamp": "Fair Price Clamp",
        "instrument.fields.fairPriceImpactDepth": "Fair Price Impact Depth",
        "instrument.fields.fundingInterval": "Funding Interval",
        "instrument.fields.fundingReferenceAt": "Funding Times",
        "instrument.fields.fundingSymbol": "Funding Index",
        "instrument.fields.incrementalM": "Incremental Margin",
        "instrument.fields.liquidationExchangeFee": "Liquidation Exchange Fee",
        "instrument.fields.liquidationExchangeFeeCap": "Liquidation Exchange Fee Cap",
        "instrument.fields.liquidationInsuranceFee": "Liquidation Insurance Fee",
        "instrument.fields.liquidationInsuranceFeeCap": "Liquidation Insurance Fee Cap",
        "instrument.fields.listedAt": "List Date",
        "instrument.fields.makerFee": "Maker Fee",
        "instrument.fields.makerFeeCap": "Maker Fee Cap",
        "instrument.fields.markIndex": "Mark Index",
        "instrument.fields.maxOrderQty": "Max Order Quantity",
        "instrument.fields.maxPositionSize": "Max Position Size",
        "instrument.fields.maxPrice": "Max Price",
        "instrument.fields.maxTradeSize": "Max Trade Size",
        "instrument.fields.minPrice": "Min Price",
        "instrument.fields.minTradeAmount": "Min Trade Amount",
        "instrument.fields.referenceIndex": "Reference Index",
        "instrument.fields.riskStep": "Risk Step",
        "instrument.fields.symbol": "Symbol",
        "instrument.fields.takerFee": "Taker Fee",
        "instrument.fields.takerFeeCap": "Taker Fee Cap",
        "instrument.fields.tickSize": "Tick Size",
        "instrument.type.future": "Future",
        "instrument.type.option": "Option",
        "instrument.type.perpetual": "Perpetual",
        "insurance.menu.title": "Insurance",
        "insurance.table.head.balance": "Balance",
        "insurance.table.head.currency": "Currency",
        "insurance.table.head.timestamp": "Timestamp",
        "modals.accessTokensConfirmation.id": "ID:",
        "modals.accessTokensConfirmation.secret": "Secret:",
        "modals.activateMfa.agreement": "I have saved the above code",
        "modals.activateMfa.buttons.submit": "Enable 2FA",
        "modals.activateMfa.text": "Download Google Authenticator, scan the QR code below and store the code offline",
        "modals.activateMfa.title": "Activate 2FA",
        "modals.amendOrder.buttons.amend": "Amend",
        "modals.amendOrder.title": "Amend Order",
        "modals.common.buttons.cancel": "Cancel",
        "modals.confirmation.buttons.resendEmail": "Resend Email",
        "modals.depositFunds.account.errors.required": "Please select your Account!",
        "modals.depositFunds.address": "Deposit address",
        "modals.depositFunds.buttons.submit": "Submit",
        "modals.depositFunds.message": "Do not send Litecoin, Bitcoin Cash, or Tether to this address!",
        "modals.depositFunds.title": "Deposit Funds",
        "modals.disableMfa.title": "Disable 2FA",
        "modals.editAccount.buttons.save": "Save",
        "modals.editAccount.currency.errors.required": "Please input your Currency!",
        "modals.editAccount.currency.placeholder": "Currency",
        "modals.editAccount.isDefault": "Primary (default) wallet",
        "modals.editAccount.name.errors.required": "Please input your Name!",
        "modals.editAccount.name.placeholder": "Alias Name",
        "modals.editAccount.title": "Edit Account",
        "modals.editTokenPermissions.account": "Account",
        "modals.editTokenPermissions.blockTrade": "Block Trade",
        "modals.editTokenPermissions.buttons.save": "Save Permissions",
        "modals.editTokenPermissions.status": "Status",
        "modals.editTokenPermissions.status.active": "Active",
        "modals.editTokenPermissions.title": "Edit Token Permissions",
        "modals.editTokenPermissions.trade": "Trade",
        "modals.editTokenPermissions.wallet": "Wallet",
        "modals.emailConfirmation.line1": "Please be patient",
        "modals.emailConfirmation.line2": "as it may require more",
        "modals.emailConfirmation.line3": "than a couple of minutes to delivery",
        "modals.emailConfirmation.title": "Email Confirmation",
        "modals.mfaInput.buttons.submit": "Submit",
        "modals.mfaInput.message": "An email has been sent to your inbox with a 6 digit code.",
        "modals.mfaInput.title": "2FA Authorisation",
        "modals.mfaReminder.buttons.enable": "Enable 2FA",
        "modals.mfaReminder.buttons.skip": "Skip",
        "modals.mfaReminder.message": "Download Google Authenticator, scan the QR code below and store the code offline",
        "modals.mfaReminder.title": "Reminder: Activate 2FA",
        "modals.newAccount.buttons.createAccount": "Create Account",
        "modals.newAccount.title": "New Account",
        "modals.orderApproval.availableBalance": "Available",
        "modals.orderApproval.buttons.submit": "Place Order",
        "modals.orderApproval.limitPrice": "Limit Price",
        "modals.orderApproval.markPrice": "Mark Price",
        "modals.orderApproval.orderSize": "Amount",
        "modals.orderApproval.takeProfitStopLoss": "Take profit/Stop loss",
        "modals.orderApproval.takeProfitStopLoss.notEnabled": "Not Enabled",
        "modals.orderApproval.title": "Order Approval",
        "modals.recoveryPasswordConfirmation.line1": "An email has been sent to your inbox",
        "modals.recoveryPasswordConfirmation.line2": "with a password recovery link.",
        "modals.recoveryPasswordConfirmation.line3": "Click on the link and change your password.",
        "modals.recoveryPasswordConfirmation.title": "Recovery Link",
        "modals.transferApproval.amount": "Amount",
        "modals.transferApproval.buttons.submit": "Approve",
        "modals.transferApproval.fromAccount": "From Account",
        "modals.transferApproval.title": "Transfer Approval",
        "modals.transferApproval.toAccount": "To Account",
        "modals.transferFunds.accountPrefix.source": "Source Account ",
        "modals.transferFunds.accountPrefix.target": "Target Account ",
        "modals.transferFunds.amount.errors.required": "Please set Amount!",
        "modals.transferFunds.amount.placeholder": "Amount",
        "modals.transferFunds.buttons.submit": "Transfer",
        "modals.transferFunds.buttons.useMax": "USE MAX",
        "modals.transferFunds.fromAccountId.errors.required": "Please select source Account!",
        "modals.transferFunds.fromAccountId.placeholder": "Select source account",
        "modals.transferFunds.title": "Transfer Funds",
        "modals.transferFunds.toAccountId.errors.required": "Please select target Account!",
        "modals.transferFunds.toAccountId.placeholder": "Select target account",
        "modals.withdrawFunds.accountId.error.required": "Please input your Account!",
        "modals.withdrawFunds.amount.error.required": "Please input your Amount!",
        "modals.withdrawFunds.amount.placeholder": "Amount",
        "modals.withdrawFunds.amount.useBaxBtn": "USE MAX",
        "modals.withdrawFunds.buttons.submit": "Withdraw",
        "modals.withdrawFunds.destAddress.error.required": "Please input your Destination Address!",
        "modals.withdrawFunds.destAddress.placeholder": "Destination Address",
        "modals.withdrawFunds.minWithdrawal": "Minimum available withdrawal is ",
        "modals.withdrawFunds.networkFee.error.minValue": "Min value is {value}",
        "modals.withdrawFunds.networkFee.error.required": "Please input your Fee!",
        "modals.withdrawFunds.networkFee.placeholder": "Network Fee",
        "modals.withdrawFunds.title": "Withdraw Funds",
        "modals.withdrawalApproval.account": "Account",
        "modals.withdrawalApproval.address": "Address",
        "modals.withdrawalApproval.amount": "Amount",
        "modals.withdrawalApproval.buttons.submit": "Approve",
        "modals.withdrawalApproval.networkFee": "Network Fee",
        "modals.withdrawalApproval.title": "Withdrawal Approval",
        "modals.withdrawalConfirmation.text": "Please be patient as it may require more than a couple of minutes to delivery",
        "modals.withdrawalConfirmation.title": "Withdrawal Confirmed",
        "notifications.apiKeyCreated": "API key created successfully",
        "notifications.apiKeyRemoved": "API token was removed successfully",
        "notifications.error.orderCanceled": "Order canceled",
        "notifications.error.transferError": "Something goes wrong with transfer",
        "notifications.errors.somethingGoesWrong": "Something goes wrong",
        "notifications.mfaEnabled": "Enabled MFA authentication!",
        "notifications.orderUpdated": "Order updated",
        "notifications.passwordChanged": "Password changed",
        "notifications.transferCreated": "Transfer created!",
        "notifications.withdrawCancelled": "Withdraw was cancelled successfully",
        "notifications.withdrawConfirmed": "Withdraw confirmed!",
        "notifications.withdrawalCreated": "Withdrawal created",
        "options.greek.gamma": "Gamma",
        "options.greek.theta": "Theta",
        "options.greek.vega": "Vega",
        "options.table.head.ask": "Ask",
        "options.table.head.bid": "Bid",
        "options.table.head.delta": "âˆ† Delta",
        "options.table.head.iv": "IV",
        "options.table.head.last": "Last",
        "options.table.head.mark": "Mark",
        "options.table.head.open": "Open",
        "options.table.head.pos": "Pos",
        "options.table.head.size": "Size",
        "options.table.head.strike": "Strike",
        "options.table.head.vol": "Vol",
        "order.actions.amend": "Amend",
        "order.create.advanced": "Advanced",
        "order.create.amount.label": "Amount",
        "order.create.amount.placeholder": "Amount",
        "order.create.available": "Available",
        "order.create.buttons.buy": "BUY ORDER",
        "order.create.buttons.sell": "SELL ORDER",
        "order.create.hiddenQty": "Hidden Qty",
        "order.create.initialMargin": "Initial Margin",
        "order.create.notification.error": "Creating order error",
        "order.create.notification.success": "Order created",
        "order.create.postOnly": "Post Only",
        "order.create.price.label": "Limit Price",
        "order.create.price.placeholder": "Limit Price",
        "order.create.reduceOnly": "Reduce Only",
        "order.create.stopLoss": "Stop Loss",
        "order.create.takeProfit": "Take Profit",
        "order.create.triggerPrice.items.index": "Index",
        "order.create.triggerPrice.items.last": "Last",
        "order.create.triggerPrice.items.mark": "Mark",
        "order.create.triggerPrice.placeholder": "Trigger Price",
        "order.side.buy": "Long (Buy)",
        "order.side.sell": "Sell (Short)",
        "order.timeInForce.fok": "Fill or Kill",
        "order.timeInForce.gtc": "Good 'Til Cancel",
        "order.timeInForce.ioc": "Immediate or Cancel",
        "orderBook.head.priceUsd": "Price (USD)",
        "orderBook.head.size": "Size",
        "orderBook.head.total": "Total",
        "orderBook.tooltip.avgPrice": "Avg. Price",
        "orderBook.tooltip.sumSize": "Sum. Size",
        "orderBook.tooltip.sumTotal": "Sum. Total",
        "ordersTable.head.accountId": "Account id",
        "ordersTable.head.action": "Action",
        "ordersTable.head.actions": "Actions",
        "ordersTable.head.avgPrice": "Avg.Price",
        "ordersTable.head.displaySize": "Display Size",
        "ordersTable.head.fillSize": "Fill Size",
        "ordersTable.head.filledSize": "Filled Size",
        "ordersTable.head.filledSizeCurrency": "Filled Size Currency",
        "ordersTable.head.instrument": "Instrument",
        "ordersTable.head.label": "Label",
        "ordersTable.head.orderId": "Order id",
        "ordersTable.head.position": "Position",
        "ordersTable.head.postReduceOnly": "Post / Reduce only",
        "ordersTable.head.price": "Price",
        "ordersTable.head.remainingSize": "Remaining Size",
        "ordersTable.head.side": "Side",
        "ordersTable.head.size": "Size",
        "ordersTable.head.status": "Status",
        "ordersTable.head.symbol": "Symbol",
        "ordersTable.head.time": "Time",
        "ordersTable.head.type": "Type",
        "overlays.signUpInvite.line1": "Please <LoginLink>Login</LoginLink> or <SignUpLink>Signup</SignUpLink>",
        "overlays.signUpInvite.line2": "to Trade",
        "passwordRecovery.buttons.submit": "Submit",
        "passwordRecovery.email.error.required": "Please input your Email Address!",
        "passwordRecovery.email.placeholder": "Email Address",
        "passwordRecovery.title": "Password Recovery",
        "positionPage.title": "Position {id}",
        "positions.actions.actions.closePrice": "Close",
        "positions.actions.actions.closePrice.input.placeholder": "Close Price",
        "positions.actions.market": "Market",
        "positionsTable.head.action": "Action",
        "positionsTable.head.avgPrice": "Avg. Price",
        "positionsTable.head.currency": "Currency",
        "positionsTable.head.estLiqPrice": "Est. Liq. Price",
        "positionsTable.head.initMargin": "Init. Margin",
        "positionsTable.head.initialMargin": "Initial Margin",
        "positionsTable.head.instrument": "Instrument",
        "positionsTable.head.maintMargin": "Maint Margin",
        "positionsTable.head.markPrice": "Mark Price",
        "positionsTable.head.positionId": "Position ID",
        "positionsTable.head.realisedPnlRoe": "Realised PNL (ROE %)",
        "positionsTable.head.realizedPl": "Realized Pl.",
        "positionsTable.head.side": "Side",
        "positionsTable.head.size": "Size",
        "positionsTable.head.sizeCurrency": "Size Currency",
        "positionsTable.head.symbol": "Symbol",
        "positionsTable.head.type": "Type",
        "positionsTable.head.unrealisedPnlRoe": "Unrealised PNL (ROE %)",
        "profile.cards.2fa": "2FA",
        "profile.cards.2faDescription": "Two-factor Authentication adds an extra layer of security to your account by asking for a verification code when you sign in\n",
        "profile.cards.accountId": "Account ID",
        "profile.cards.accountSettings": "Account Settings",
        "profile.cards.accountSettings.changePassword": "Change Password",
        "profile.cards.displayMode": "Display Mode",
        "profile.cards.email": "Email",
        "profile.cards.language": "Language",
        "profile.cards.password": "Password",
        "profile.cards.preferences": "Preferences",
        "profile.header": "Profile",
        "publicTrades.table.head.price": "Price (USD)",
        "publicTrades.table.head.size": "Size",
        "publicTrades.table.head.time": "Time",
        "references.indices.breakdown": "Historical Composite Breakdown",
        "references.instrument.specification.delivery": "Delivery",
        "references.instrument.specification.fees": "Fees",
        "references.instrument.specification.funding": "Funding",
        "references.instrument.specification.mark": "Mark Index and Pricing",
        "references.instrument.specification.riskLimit": "Risk Limits and Margin",
        "references.menu.api": "API Explorer",
        "references.menu.contracts": "Contracts",
        "references.menu.funding": "Funding",
        "references.menu.indices": "Indices",
        "references.menu.instrument.overview": "Overview",
        "references.menu.instrument.specification": "Specification",
        "references.menu.insurance": "Insurance",
        "references.menu.settlement": "Settlement",
        "selectInstrument.table.head.expiry": "Expiry",
        "selectInstrument.table.head.lastPrice": "Last Price",
        "selectInstrument.table.head.symbol": "Symbol",
        "selectInstrument.table.head.type": "Type",
        "settlement.menu.title": "Settlement",
        "settlement.table.head.createdAt": "Created At",
        "settlement.table.head.markPrice": "Mark Price",
        "settlement.table.head.price": "Price",
        "settlement.table.head.strike_price": "Strike Price",
        "settlement.table.head.symbol": "Symbol",
        "settlement.table.head.timestamp": "Timestamp",
        "settlement.table.head.type": "type",
        "settlement.table.head.updatedAt": "Updated At",
        "statusBar.status.error": "Partially active or something",
        "statusBar.status.ok": "All systems operational",
        "symbol.breakdown.list.head.ask": "Ask",
        "symbol.breakdown.list.head.bid": "Bid",
        "symbol.breakdown.list.head.provider": "Provider",
        "symbol.breakdown.list.head.time": "Time",
        "symbol.breakdown.list.head.type": "Type",
        "symbol.breakdown.list.head.weight": "Weight",
        "taskbar.setting": "Settings",
        "taskbar.setting.items.darkTheme": "Dark theme",
        "taskbar.setting.items.resetLayouts": "Reset layouts to default",
        "transactions.table.head.action": "action",
        "transactions.table.head.baseCashflow": "base_cashflow",
        "transactions.table.head.cashflow": "cashflow",
        "transactions.table.head.createdAt": "created at",
        "transactions.table.head.currency": "currency",
        "transactions.table.head.description": "description",
        "transactions.table.head.fee": "fee",
        "transactions.table.head.id": "ID",
        "transactions.table.head.insuranceFee": "insurance_fee",
        "transactions.table.head.symbol": "symbol",
        "transactions.table.head.type": "Type",
        "transactions.title.deposits": "Deposits",
        "transactions.title.referralsIn": "Referrals In",
        "transactions.title.referralsOut": "Referrals Out",
        "transactions.title.transactions": "Transactions",
        "transactions.title.transfersIn": "Transfers In",
        "transactions.title.transfersOut": "Transfers Out",
        "transactions.title.withdrawals": "Withdrawals",
        "userMenu.items.accounts": "Trading Accounts",
        "userMenu.items.deposit": "Deposit",
        "userMenu.items.settings": "Settings",
        "userMenu.menu.transfer": "Transfer",
        "userMenu.menu.withdrawal": "Withdrawal",
        "verification.table.head.fileName": "File Name",
        "wallet.menu.title": "Wallets",
        "wallet.table.head.id": "id",
        "widget.indicator.groups.createOrder": "Create Order",
        "widget.indicator.groups.private": "Private",
        "widget.indicator.groups.public": "Public",
        "widget.indicator.newForm.account": "Account",
        "widget.indicator.newForm.account.placeholder": "Use the current account",
        "widget.indicator.newForm.buttons.create": "Add Indicator",
        "widget.indicator.newForm.indicator": "Indicator",
        "widget.indicator.newForm.indicator.error": "Please specify the indicator first",
        "widget.indicator.newForm.instrument": "Instrument",
        "widget.indicator.newForm.instrument.placeholder": "Use the navigation one",
        "widget.indicator.title.accountSummary": "Account Summary",
        "widget.indicator.title.accountTrades": "Trade History",
        "widget.indicator.title.chart": "Chart",
        "widget.indicator.title.chartDepths": "Chart Depths",
        "widget.indicator.title.closedOrders": "Order History",
        "widget.indicator.title.contractDetails": "Contract Details",
        "widget.indicator.title.createLimitOrder": "LIMIT",
        "widget.indicator.title.createMarketOrder": "MARKET",
        "widget.indicator.title.new": "New",
        "widget.indicator.title.openOrders": "Open Orders",
        "widget.indicator.title.optionsBoard": "Options Board",
        "widget.indicator.title.orderBook": "Order Book",
        "widget.indicator.title.positions": "Positions",
        "widget.indicator.title.publicTrades": "Trade History",
        "withdrawals.table.head.accountId": "Account Id",
        "withdrawals.table.head.actions": "Actions",
        "withdrawals.table.head.address": "Address",
        "withdrawals.table.head.amount": "amount",
        "withdrawals.table.head.createdAt": "created At",
        "withdrawals.table.head.networkFee": "network fee",
        "withdrawals.table.head.state": "state",
        "withdrawals.table.head.transactionId": "Transaction ID",
        "withdrawals.table.head.vOut": "v_out",
        "withdrawals.table.head.withdrawId": "Withdraw ID"
      }
    }
  }
